-- ============================================================
-- SOLO LEAGUE RPG — Database Setup, Step 2
-- Floating chat widget messages
-- HOW TO RUN THIS: same as before — Supabase → SQL Editor →
-- New query → paste this in → Run
-- ============================================================

create table chat_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references auth.users not null,
  sender_name text not null,
  message text not null,
  created_at timestamptz default now()
);

-- Turn on Row Level Security
alter table chat_messages enable row level security;

-- Anyone logged in can READ all messages (it's a shared chat room)
create policy "Logged in players can read chat"
  on chat_messages for select
  to authenticated
  using (true);

-- A player can only send messages AS THEMSELVES
-- (stops anyone from faking messages from another player)
create policy "Players can send their own messages"
  on chat_messages for insert
  to authenticated
  with check (auth.uid() = sender_id);

-- Turn on realtime so messages appear instantly for everyone,
-- without needing to refresh the page
alter publication supabase_realtime add table chat_messages;
